apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-aws-k8s-learn
spec:
  selector:
    matchLabels:
      app: spring-aws-k8s-learn
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-aws-k8s-learn
    spec:
      containers:
      - name: spring-aws-k8s-learn
        image: 992382425597.dkr.ecr.us-east-1.amazonaws.com/dev/spring-aws-k8s-learn:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: spring-aws-k8s-learn

